Config:
  version: "0.2"
  description: "Configuration file for the VectorDB project"

Database:
  model_name: "faiss"
  index_filename: "faiss.index"
  metadata_filename: "faiss_metadata.json"

Embedding:
  model_name: "KBLab/sentence-bert-swedish-cased"

VectorStore:
  index_dir: "data"