Config:
  version: "0.4"
  description: "Configuration file for the VectorDB project"

Database:
  model_name: "faiss"
  index_filename: "faiss.index"
  metadata_filename: "faiss_metadata.json"

Embedding:
  model_name: "jhu-clsp/mmBERT-base"

VectorStore:
  index_dir: "data"