Config:
  version: "0.3"
  description: "Configuration file for the VectorDB project"

Database:
  model_name: "faiss"
  index_filename: "faiss.index"
  metadata_filename: "faiss_metadata.json"

Embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

VectorStore:
  index_dir: "data"